-- ============================================================================
-- PROJECT ATHENA: SUPABASE SCHEMA v3.0
-- ============================================================================
-- Aligned with Engineering Design Document v3.0
-- 
-- Run in: Supabase Dashboard → SQL Editor → New Query
-- 
-- Tables:
--   1. memory_logs     - Full conversation history
--   2. agent_states    - Agent key-value persistence
--   3. user_facts      - Evolution table (learned preferences)
--   4. agent_registry  - Sub-agent orchestration
--   5. athena_monologue - Thought analysis
--   6. file_storage    - File/backup tracking
-- ============================================================================

-- ============================================================================
-- 1. MEMORY_LOGS (Episodic Memory / Chat History)
-- ============================================================================
-- Stores full conversation history for context injection

CREATE TABLE IF NOT EXISTS memory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    user_input TEXT NOT NULL,
    athena_response TEXT NOT NULL,
    summary TEXT,                           -- For semantic search
    intent TEXT,                            -- question, command, chat
    sentiment TEXT,                         -- positive, neutral, negative
    tokens_used INTEGER DEFAULT 0,
    source TEXT DEFAULT 'telegram',         -- telegram, cli, api
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_memory_logs_created ON memory_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_logs_session ON memory_logs(session_id);

ALTER TABLE memory_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Full access to memory_logs" ON memory_logs FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 2. AGENT_STATES (Key-Value Store for Agents)
-- ============================================================================
-- Allows agents to persist state (e.g., "last_video_checked")

CREATE TABLE IF NOT EXISTS agent_states (
    agent_name TEXT NOT NULL,
    key TEXT NOT NULL,
    value JSONB DEFAULT '{}'::JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    PRIMARY KEY (agent_name, key)
);

CREATE OR REPLACE FUNCTION update_agent_states_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_agent_states_modtime
    BEFORE UPDATE ON agent_states
    FOR EACH ROW
    EXECUTE FUNCTION update_agent_states_timestamp();

ALTER TABLE agent_states ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Full access to agent_states" ON agent_states FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 3. USER_FACTS (The Evolution Table)
-- ============================================================================
-- Stores learned preferences for the "Trend Spotter" system
-- Examples: "current_interest" = "Anime", "financial_mode" = "aggressive_saving"

CREATE TABLE IF NOT EXISTS user_facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value JSONB NOT NULL,
    category TEXT DEFAULT 'preference',    -- preference, personal, technical, goal
    confidence REAL DEFAULT 1.0,           -- How sure Athena is (0.0 - 1.0)
    source TEXT DEFAULT 'inference',       -- inference, explicit, system
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE OR REPLACE FUNCTION update_user_facts_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_user_facts_modtime
    BEFORE UPDATE ON user_facts
    FOR EACH ROW
    EXECUTE FUNCTION update_user_facts_timestamp();

CREATE INDEX IF NOT EXISTS idx_user_facts_category ON user_facts(category);

ALTER TABLE user_facts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Full access to user_facts" ON user_facts FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 4. AGENT_REGISTRY (Sub-Agent Orchestration)
-- ============================================================================
-- Tracks spawned agents, their status, and outputs

CREATE TABLE IF NOT EXISTS agent_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id TEXT UNIQUE NOT NULL,
    agent_name TEXT NOT NULL,
    task_description TEXT,
    status TEXT DEFAULT 'pending',          -- pending, running, completed, failed
    priority INTEGER DEFAULT 5,
    last_output TEXT,
    error_message TEXT,
    retry_count INTEGER DEFAULT 0,
    metadata JSONB DEFAULT '{}'::JSONB,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_registry_status ON agent_registry(status);
CREATE INDEX IF NOT EXISTS idx_agent_registry_name ON agent_registry(agent_name);

ALTER TABLE agent_registry ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Full access to agent_registry" ON agent_registry FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 5. ATHENA_MONOLOGUE (Thought Analysis)
-- ============================================================================
-- Logs Athena's internal thinking for debugging/learning

CREATE TABLE IF NOT EXISTS athena_monologue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    thought_process TEXT NOT NULL,
    action_taken TEXT,
    category TEXT DEFAULT 'analysis',       -- analysis, decision, error, learning
    success_score INTEGER CHECK (success_score >= 1 AND success_score <= 5),
    tokens_used INTEGER DEFAULT 0,
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_monologue_created ON athena_monologue(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_monologue_success ON athena_monologue(success_score);

ALTER TABLE athena_monologue ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Full access to athena_monologue" ON athena_monologue FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 6. FILE_STORAGE (Backup/File Tracking)
-- ============================================================================

CREATE TABLE IF NOT EXISTS file_storage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    storage_type TEXT DEFAULT 'local',      -- gcs, local
    file_type TEXT,                         -- backup, screenshot, image
    file_size_bytes BIGINT,
    mime_type TEXT,
    description TEXT,
    source TEXT DEFAULT 'system',
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_file_storage_type ON file_storage(file_type);

ALTER TABLE file_storage ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Full access to file_storage" ON file_storage FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 7. INFLUENCE_CLOUD (Causality Engine - Media → Purchase Tracking)
-- ============================================================================
-- Stores keywords from media consumption to track purchase inspirations
-- Example: After watching "Bleach", stores ["sword", "katana", "figure"]

CREATE TABLE IF NOT EXISTS influence_cloud (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,               -- Anime, YouTube, Book, Podcast
    title TEXT NOT NULL,                -- The specific content title
    category TEXT DEFAULT 'media',      -- media, tech, research, lifestyle
    keywords TEXT[] NOT NULL,           -- Associated purchasable keywords
    consumed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_influence_cloud_expires ON influence_cloud(expires_at);
CREATE INDEX IF NOT EXISTS idx_influence_cloud_category ON influence_cloud(category);
CREATE INDEX IF NOT EXISTS idx_influence_cloud_keywords ON influence_cloud USING GIN(keywords);

ALTER TABLE influence_cloud ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Full access to influence_cloud" ON influence_cloud FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 8. PRECOMPUTED_FEATURES (Analytics Cache)
-- ============================================================================
-- Stores precomputed daily/weekly analytics to avoid re-reading everything

CREATE TABLE IF NOT EXISTS precomputed_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,             -- spending, habits, social, health
    feature_name TEXT NOT NULL,         -- weekly_avg_spending, sleep_consistency
    feature_value JSONB NOT NULL,       -- The computed value
    period_start DATE,                  -- Start of period this covers
    period_end DATE,                    -- End of period
    computed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(category, feature_name, period_start)
);

CREATE INDEX IF NOT EXISTS idx_features_category ON precomputed_features(category);
CREATE INDEX IF NOT EXISTS idx_features_expires ON precomputed_features(expires_at);

ALTER TABLE precomputed_features ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Full access to precomputed_features" ON precomputed_features FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 9. ANALYSIS_AUDIT (Evidence-Based Conclusions Audit Trail)
-- ============================================================================
-- Logs every data access for transparency - "show receipts" philosophy

CREATE TABLE IF NOT EXISTS analysis_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    query TEXT,                         -- What was asked
    analysis_mode TEXT,                 -- finance, health, schedule, learning
    data_sources TEXT[],                -- Which tables/files were accessed
    records_accessed INTEGER DEFAULT 0,
    conclusion TEXT,                    -- The generated conclusion
    confidence REAL,                    -- 0.0 - 1.0
    evidence_summary JSONB,             -- Summary of supporting evidence
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_created ON analysis_audit(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_mode ON analysis_audit(analysis_mode);

ALTER TABLE analysis_audit ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Full access to analysis_audit" ON analysis_audit FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 10. PURCHASE_ATTRIBUTIONS (Causality Engine Results)
-- ============================================================================
-- Stores detected links between purchases and their inspirations

CREATE TABLE IF NOT EXISTS purchase_attributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name TEXT NOT NULL,
    amount DECIMAL(10,2),
    purchase_date TIMESTAMP WITH TIME ZONE,
    influence_source TEXT,              -- What inspired it (e.g., "Bleach")
    influence_category TEXT,            -- anime, tech, book, etc.
    matched_keywords TEXT[],            -- Which keywords matched
    confidence REAL DEFAULT 0.0,        -- 0.0 - 1.0
    days_after_consumption INTEGER,     -- How many days after consuming the media
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_attributions_source ON purchase_attributions(influence_source);
CREATE INDEX IF NOT EXISTS idx_attributions_category ON purchase_attributions(influence_category);

ALTER TABLE purchase_attributions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Full access to purchase_attributions" ON purchase_attributions FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 11. INITIAL USER FACTS (Drew's Profile)
-- ============================================================================
-- Core persona data - the "Evolution" baseline

INSERT INTO user_facts (key, value, category, source) VALUES
    ('name', '"Drew"', 'personal', 'system'),
    ('location', '{"city": "Minneapolis", "state": "Minnesota", "timezone": "America/Chicago"}', 'personal', 'system'),
    ('pets', '[{"name": "Sushi", "type": "cat"}, {"name": "Astro", "type": "cat"}]', 'personal', 'system'),
    ('partner', '{"name": "Skylar"}', 'personal', 'system'),
    ('pc_setup', '{"os": "Windows 11", "shell": "PowerShell"}', 'technical', 'system'),
    ('debt_goal', '{"amount": 8500, "target_date": "2026-03-01", "mode": "aggressive_saving"}', 'goal', 'system'),
    ('interests', '["anime", "tech", "gaming", "AI", "finance"]', 'preference', 'system'),
    ('favorite_anime', '["One Piece", "Bleach", "Naruto"]', 'preference', 'system'),
    ('current_movie_preference', '"Anime/Shonen"', 'preference', 'inference'),
    ('current_financial_mode', '"aggressive_saving"', 'preference', 'inference'),
    ('detected_mood', '"focused"', 'preference', 'inference')
ON CONFLICT (key) DO UPDATE SET 
    value = EXCLUDED.value,
    updated_at = NOW();

-- ============================================================================
-- VERIFICATION
-- ============================================================================

SELECT 'memory_logs' as table_name, COUNT(*) as rows FROM memory_logs
UNION ALL SELECT 'agent_states', COUNT(*) FROM agent_states
UNION ALL SELECT 'user_facts', COUNT(*) FROM user_facts
UNION ALL SELECT 'agent_registry', COUNT(*) FROM agent_registry
UNION ALL SELECT 'athena_monologue', COUNT(*) FROM athena_monologue
UNION ALL SELECT 'file_storage', COUNT(*) FROM file_storage
UNION ALL SELECT 'influence_cloud', COUNT(*) FROM influence_cloud
UNION ALL SELECT 'precomputed_features', COUNT(*) FROM precomputed_features
UNION ALL SELECT 'analysis_audit', COUNT(*) FROM analysis_audit
UNION ALL SELECT 'purchase_attributions', COUNT(*) FROM purchase_attributions;

-- View user facts
SELECT key, value, category, source FROM user_facts ORDER BY category, key;
