-- ============================================================================
-- ATHENA 2.0 MASTER SCHEMA (Cloud-First Architecture)
-- ============================================================================
-- Run this entire script in your Supabase SQL Editor.
-- It works safely even if you run it multiple times (idempotent).

-- ----------------------------------------------------------------------------
-- 0. CLEANUP (Force Schema Update for v2)
-- ----------------------------------------------------------------------------
-- We drop these specifically to ensure the new columns (timestamp_utc, context_state) exist.
DROP TABLE IF EXISTS unified_events CASCADE;
DROP TABLE IF EXISTS memories_semantic CASCADE;
DROP TABLE IF EXISTS memories_episodic CASCADE;
DROP TABLE IF EXISTS context_state CASCADE;
DROP TABLE IF EXISTS patterns_registry CASCADE;

-- ----------------------------------------------------------------------------
-- 0. EXTENSIONS
-- ----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ----------------------------------------------------------------------------
-- 1. CORE MEMORY & EVENTS (The "Brain")
-- ----------------------------------------------------------------------------

-- 1.1 Unified Event Timeline (Source of Truth for Life Events)
-- Replaces disparate logs. Tracks transactions, watches, sessions.
CREATE TABLE IF NOT EXISTS unified_events (
    event_id TEXT PRIMARY KEY,          -- Deterministic Hash (source:id)
    event_type TEXT NOT NULL,           -- USER_MESSAGE, TASK_CREATED, TRANSACTION, WATCH
    source TEXT NOT NULL,               -- telegram, gmail, youtube
    timestamp_utc TIMESTAMP WITH TIME ZONE NOT NULL,
    actor TEXT DEFAULT 'drew',
    privacy_level TEXT DEFAULT 'MED',
    raw_ref TEXT,                       -- Pointer to Vault (GCS)
    data JSONB DEFAULT '{}'::JSONB,     -- The detail payload
    derived JSONB DEFAULT '{}'::JSONB,  -- Computed features
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_events_ts ON unified_events(timestamp_utc DESC);
CREATE INDEX IF NOT EXISTS idx_events_type ON unified_events(event_type);

-- 1.2 Semantic Memory (Facts & Preferences)
-- Long-term knowledge graph.
CREATE TABLE IF NOT EXISTS memories_semantic (
    fact_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    key TEXT,                           -- "coffee_preference"
    value JSONB NOT NULL,               -- "black" or {"type": "black"}
    category TEXT NOT NULL,             -- preference, goal, constraint
    confidence FLOAT DEFAULT 1.0,
    source_event_ids TEXT[],            -- Array of event_id references
    last_accessed TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    embedding VECTOR(1536)              -- For AI retrieval
);

-- 1.5 Context State (Short-term Conversation Stack)
-- Tracks active entities for pronoun resolution ("there", "at 8")
CREATE TABLE IF NOT EXISTS context_state (
    chat_id TEXT PRIMARY KEY,
    active_task_id TEXT,
    active_intent TEXT,
    active_entities JSONB DEFAULT '[]'::JSONB,    -- [{"type": "loc", "val": "Roseville", "ts": "..."}]
    last_locations JSONB DEFAULT '[]'::JSONB,
    last_times JSONB DEFAULT '[]'::JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 1.3 Episodic Memory (Daily Capsules)
-- Summarized history.
CREATE TABLE IF NOT EXISTS memories_episodic (
    episode_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    date DATE UNIQUE NOT NULL,
    summary TEXT NOT NULL,
    highlights JSONB DEFAULT '{}'::JSONB,
    embedding VECTOR(1536),             -- For finding similar days
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 1.4 Patterns Registry
-- Detected habits and cognitive modes.
CREATE TABLE IF NOT EXISTS patterns_registry (
    pattern_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,                 -- "Late Night Doomscroll"
    type TEXT NOT NULL,                 -- motif, association, mode
    confidence FLOAT,
    status TEXT DEFAULT 'hypothesis',   -- hypothesis, confirmed, rejected
    meta JSONB DEFAULT '{}'::JSONB,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 2. OPERATION & AGENTS (The "Body")
-- ----------------------------------------------------------------------------

-- 2.1 Agent Registry
-- Tracks specialized agents (e.g. "Inbox Pilot").
CREATE TABLE IF NOT EXISTS agent_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'idle',
    last_run_at TIMESTAMP WITH TIME ZONE,
    metadata JSONB DEFAULT '{}'::JSONB
);

-- 2.2 Chat History (Raw Logs)
-- The literal conversation text (for training/debug).
CREATE TABLE IF NOT EXISTS memory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    role TEXT NOT NULL,                 -- user, assistant
    content TEXT NOT NULL,
    tokens_used INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2.3 Monologue (Thought Process)
-- Internal Chain-of-Thought logs.
CREATE TABLE IF NOT EXISTS athena_monologue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    thought_process TEXT,
    action_taken TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 3. PERMISSIONS (Row Level Security)
-- ----------------------------------------------------------------------------
ALTER TABLE unified_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE memories_semantic ENABLE ROW LEVEL SECURITY;
ALTER TABLE memories_episodic ENABLE ROW LEVEL SECURITY;
ALTER TABLE patterns_registry ENABLE ROW LEVEL SECURITY;

-- Allow full access to service_role (Athena)
CREATE POLICY "Service Role Full Access" ON unified_events FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access" ON memories_semantic FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access" ON memories_episodic FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access" ON patterns_registry FOR ALL TO service_role USING (true) WITH CHECK (true);

-- (Optional) Add public read capabilities if building a frontend later
