-- ============================================================================
-- UNIFIED ATHENA PROJECT SUPABASE SCHEMA
-- Contains:
-- 1. Core Athena Agents (Memory, Facts, Monologue)
-- 2. Hakari/Parlay Agents (Events, Slips, stats)
-- ============================================================================

-- Enable UUID extension (Required for Hakari, good for all)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- SECTION A: CORE ATHENA TABLES
-- ============================================================================

-- 1. MEMORY_LOGS (Episodic Memory / Chat History)
CREATE TABLE IF NOT EXISTS memory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    user_input TEXT NOT NULL,
    athena_response TEXT NOT NULL,
    summary TEXT,
    intent TEXT,
    sentiment TEXT,
    tokens_used INTEGER DEFAULT 0,
    source TEXT DEFAULT 'telegram',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- MIGRATION: Ensure columns exist if table was already there
DO $$ 
BEGIN 
    BEGIN
        ALTER TABLE memory_logs ADD COLUMN session_id TEXT;
    EXCEPTION
        WHEN duplicate_column THEN NULL;
    END;
    BEGIN
        ALTER TABLE memory_logs ADD COLUMN source TEXT DEFAULT 'telegram';
    EXCEPTION
        WHEN duplicate_column THEN NULL;
    END;
END $$;

CREATE INDEX IF NOT EXISTS idx_memory_logs_created ON memory_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_logs_session ON memory_logs(session_id);

ALTER TABLE memory_logs ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to memory_logs" ON memory_logs;
    CREATE POLICY "Full access to memory_logs" ON memory_logs FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 2. AGENT_STATES (Key-Value Store for Agents)
CREATE TABLE IF NOT EXISTS agent_states (
    agent_name TEXT NOT NULL,
    key TEXT NOT NULL,
    value JSONB DEFAULT '{}'::JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    PRIMARY KEY (agent_name, key)
);

CREATE OR REPLACE FUNCTION update_agent_states_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_agent_states_modtime ON agent_states;
CREATE TRIGGER update_agent_states_modtime
    BEFORE UPDATE ON agent_states
    FOR EACH ROW
    EXECUTE FUNCTION update_agent_states_timestamp();

ALTER TABLE agent_states ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to agent_states" ON agent_states;
    CREATE POLICY "Full access to agent_states" ON agent_states FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 3. USER_FACTS (The Evolution Table)
CREATE TABLE IF NOT EXISTS user_facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value JSONB NOT NULL,
    category TEXT DEFAULT 'preference',    -- preference, personal, technical, goal
    confidence REAL DEFAULT 1.0,           -- How sure Athena is (0.0 - 1.0)
    source TEXT DEFAULT 'inference',       -- inference, explicit, system
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE OR REPLACE FUNCTION update_user_facts_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_user_facts_modtime ON user_facts;
CREATE TRIGGER update_user_facts_modtime
    BEFORE UPDATE ON user_facts
    FOR EACH ROW
    EXECUTE FUNCTION update_user_facts_timestamp();

CREATE INDEX IF NOT EXISTS idx_user_facts_category ON user_facts(category);

ALTER TABLE user_facts ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    DROP POLICY IF EXISTS "Full access to user_facts" ON user_facts;
    CREATE POLICY "Full access to user_facts" ON user_facts FOR ALL USING (true) WITH CHECK (true);
END $$;

-- MIGRATION: Ensure unique key for ON CONFLICT support
DO $$ 
BEGIN 
    -- 1. Deduplicate keys (keeping latest)
    DELETE FROM user_facts 
    WHERE id IN (
        SELECT id FROM (
            SELECT id, ROW_NUMBER() OVER (partition BY key ORDER BY id DESC) AS rnum 
            FROM user_facts
        ) t 
        WHERE t.rnum > 1
    );
    
    -- 2. Create unique index (required for ON CONFLICT (key))
    CREATE UNIQUE INDEX IF NOT EXISTS idx_user_facts_unique_key ON user_facts(key);
END $$;

-- 4. AGENT_REGISTRY (Sub-Agent Orchestration)
CREATE TABLE IF NOT EXISTS agent_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id TEXT UNIQUE NOT NULL,
    agent_name TEXT NOT NULL,
    task_description TEXT,
    status TEXT DEFAULT 'pending',          -- pending, running, completed, failed
    priority INTEGER DEFAULT 5,
    last_output TEXT,
    error_message TEXT,
    retry_count INTEGER DEFAULT 0,
    metadata JSONB DEFAULT '{}'::JSONB,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_registry_status ON agent_registry(status);
CREATE INDEX IF NOT EXISTS idx_agent_registry_name ON agent_registry(agent_name);

ALTER TABLE agent_registry ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to agent_registry" ON agent_registry;
    CREATE POLICY "Full access to agent_registry" ON agent_registry FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 5. ATHENA_MONOLOGUE (Thought Analysis)
CREATE TABLE IF NOT EXISTS athena_monologue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    thought_process TEXT NOT NULL,
    action_taken TEXT,
    category TEXT DEFAULT 'analysis',       -- analysis, decision, error, learning
    success_score INTEGER CHECK (success_score >= 1 AND success_score <= 5),
    tokens_used INTEGER DEFAULT 0,
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- MIGRATION: Ensure columns exist
DO $$ 
BEGIN 
    BEGIN
        ALTER TABLE athena_monologue ADD COLUMN session_id TEXT;
    EXCEPTION
        WHEN duplicate_column THEN NULL;
    END;
END $$;

CREATE INDEX IF NOT EXISTS idx_monologue_created ON athena_monologue(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_monologue_success ON athena_monologue(success_score);

ALTER TABLE athena_monologue ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to athena_monologue" ON athena_monologue;
    CREATE POLICY "Full access to athena_monologue" ON athena_monologue FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 6. FILE_STORAGE (Backup/File Tracking)
CREATE TABLE IF NOT EXISTS file_storage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    storage_type TEXT DEFAULT 'local',      -- gcs, local
    file_type TEXT,                         -- backup, screenshot, image
    file_size_bytes BIGINT,
    mime_type TEXT,
    description TEXT,
    source TEXT DEFAULT 'system',
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_file_storage_type ON file_storage(file_type);

ALTER TABLE file_storage ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to file_storage" ON file_storage;
    CREATE POLICY "Full access to file_storage" ON file_storage FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 7. INFLUENCE_CLOUD (Causality Engine)
CREATE TABLE IF NOT EXISTS influence_cloud (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,               -- Anime, YouTube, Book, Podcast
    title TEXT NOT NULL,                -- The specific content title
    category TEXT DEFAULT 'media',      -- media, tech, research, lifestyle
    keywords TEXT[] NOT NULL,           -- Associated purchasable keywords
    consumed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_influence_cloud_expires ON influence_cloud(expires_at);
CREATE INDEX IF NOT EXISTS idx_influence_cloud_category ON influence_cloud(category);
CREATE INDEX IF NOT EXISTS idx_influence_cloud_keywords ON influence_cloud USING GIN(keywords);

ALTER TABLE influence_cloud ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to influence_cloud" ON influence_cloud;
    CREATE POLICY "Full access to influence_cloud" ON influence_cloud FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 8. PRECOMPUTED_FEATURES (Analytics Cache)
CREATE TABLE IF NOT EXISTS precomputed_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,             -- spending, habits, social, health
    feature_name TEXT NOT NULL,         -- weekly_avg_spending, sleep_consistency
    feature_value JSONB NOT NULL,       -- The computed value
    period_start DATE,                  -- Start of period this covers
    period_end DATE,                    -- End of period
    computed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(category, feature_name, period_start)
);

CREATE INDEX IF NOT EXISTS idx_features_category ON precomputed_features(category);
CREATE INDEX IF NOT EXISTS idx_features_expires ON precomputed_features(expires_at);

ALTER TABLE precomputed_features ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to precomputed_features" ON precomputed_features;
    CREATE POLICY "Full access to precomputed_features" ON precomputed_features FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 9. ANALYSIS_AUDIT (Transparency)
CREATE TABLE IF NOT EXISTS analysis_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    query TEXT,                         -- What was asked
    analysis_mode TEXT,                 -- finance, health, schedule, learning
    data_sources TEXT[],                -- Which tables/files were accessed
    records_accessed INTEGER DEFAULT 0,
    conclusion TEXT,                    -- The generated conclusion
    confidence REAL,                    -- 0.0 - 1.0
    evidence_summary JSONB,             -- Summary of supporting evidence
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- MIGRATION: Ensure columns exist
DO $$ 
BEGIN 
    BEGIN
        ALTER TABLE analysis_audit ADD COLUMN session_id TEXT;
    EXCEPTION
        WHEN duplicate_column THEN NULL;
    END;
END $$;

CREATE INDEX IF NOT EXISTS idx_audit_created ON analysis_audit(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_mode ON analysis_audit(analysis_mode);

ALTER TABLE analysis_audit ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to analysis_audit" ON analysis_audit;
    CREATE POLICY "Full access to analysis_audit" ON analysis_audit FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 10. PURCHASE_ATTRIBUTIONS (Causality Results)
CREATE TABLE IF NOT EXISTS purchase_attributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name TEXT NOT NULL,
    amount DECIMAL(10,2),
    purchase_date TIMESTAMP WITH TIME ZONE,
    influence_source TEXT,              -- What inspired it
    influence_category TEXT,            -- anime, tech, book, etc.
    matched_keywords TEXT[],            -- Which keywords matched
    confidence REAL DEFAULT 0.0,        -- 0.0 - 1.0
    days_after_consumption INTEGER,     -- How many days after
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_attributions_source ON purchase_attributions(influence_source);
CREATE INDEX IF NOT EXISTS idx_attributions_category ON purchase_attributions(influence_category);

ALTER TABLE purchase_attributions ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to purchase_attributions" ON purchase_attributions;
    CREATE POLICY "Full access to purchase_attributions" ON purchase_attributions FOR ALL USING (true) WITH CHECK (true);
END $$;

-- ============================================================================
-- SECTION B: HAKARI / PARLAY AGENT TABLES
-- ============================================================================

-- 11. HAKARI_EVENTS (Betting Decision Log)
CREATE TABLE IF NOT EXISTS hakari_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ts TIMESTAMPTZ DEFAULT now(),
    instance_id TEXT NOT NULL,
    event_type TEXT NOT NULL, -- 'decision_made', 'result_recorded', 'policy_updated'
    platform TEXT,            -- 'prizepicks', 'underdog'
    mode TEXT,                -- 'autonomous', 'assisted', 'shadow'
    slip_id TEXT,             -- Correlates events for one slip
    event_version INTEGER DEFAULT 1,
    payload JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hakari_events_ts ON hakari_events(ts DESC);
CREATE INDEX IF NOT EXISTS idx_hakari_events_slip_id ON hakari_events(slip_id);
CREATE INDEX IF NOT EXISTS idx_hakari_events_type ON hakari_events(event_type);
CREATE INDEX IF NOT EXISTS idx_hakari_events_instance ON hakari_events(instance_id);

ALTER TABLE hakari_events ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to hakari_events" ON hakari_events;
    CREATE POLICY "Full access to hakari_events" ON hakari_events FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 12. HAKARI_SLIPS (Summary View)
CREATE TABLE IF NOT EXISTS hakari_slips (
    slip_id TEXT PRIMARY KEY,
    ts_created TIMESTAMPTZ DEFAULT now(),
    platform TEXT,
    mode TEXT,
    legs_count INTEGER,
    stake NUMERIC,
    submitted BOOLEAN DEFAULT FALSE,
    outcome TEXT DEFAULT 'PENDING', -- 'WON', 'LOST', 'PUSH'
    money_won_lost NUMERIC DEFAULT 0,
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_hakari_slips_ts ON hakari_slips(ts_created DESC);

ALTER TABLE hakari_slips ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to hakari_slips" ON hakari_slips;
    CREATE POLICY "Full access to hakari_slips" ON hakari_slips FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 13. HAKARI ANALYTICS VIEWS
CREATE OR REPLACE VIEW v_hit_rate_by_stat AS
SELECT 
    e.platform,
    l->>'stat' as stat_type,
    count(*) as total_legs,
    sum(case when (l->>'hit')::boolean then 1 else 0 end) as hits,
    round(sum(case when (l->>'hit')::boolean then 1 else 0 end)::numeric / count(*), 3) as hit_rate
FROM hakari_events e,
     jsonb_array_elements(e.payload->'results') as l
WHERE e.event_type = 'result_recorded'
GROUP BY 1, 2
ORDER BY 3 DESC;

CREATE OR REPLACE VIEW v_roi_by_risk_tag AS
SELECT 
    t as risk_tag,
    count(distinct e.slip_id) as slips_involved,
    sum((e.payload->>'money_won_lost')::numeric) as total_pnl
FROM hakari_events e
JOIN hakari_events d ON d.slip_id = e.slip_id AND d.event_type = 'decision_made',
     jsonb_array_elements_text(d.payload->'thresholds_used'->'risk_tags') as t
WHERE e.event_type = 'result_recorded'
GROUP BY 1
ORDER BY 3 DESC;

-- ============================================================================
-- SECTION C: INITIAL DATA (Idempotent)
-- ============================================================================

INSERT INTO user_facts (key, value, category, source) VALUES
    ('name', '"Drew"', 'personal', 'system'),
    ('location', '{"city": "Minneapolis", "state": "Minnesota", "timezone": "America/Chicago"}', 'personal', 'system'),
    ('pets', '[{"name": "Sushi", "type": "cat"}, {"name": "Astro", "type": "cat"}]', 'personal', 'system'),
    ('partner', '{"name": "Skylar"}', 'personal', 'system'),
    ('pc_setup', '{"os": "Windows 11", "shell": "PowerShell"}', 'technical', 'system'),
    ('debt_goal', '{"amount": 8500, "target_date": "2026-03-01", "mode": "aggressive_saving"}', 'goal', 'system'),
    ('interests', '["anime", "tech", "gaming", "AI", "finance"]', 'preference', 'system'),
    ('favorite_anime', '["One Piece", "Bleach", "Naruto"]', 'preference', 'system'),
    ('current_movie_preference', '"Anime/Shonen"', 'preference', 'inference'),
    ('current_financial_mode', '"aggressive_saving"', 'preference', 'inference'),
    ('detected_mood', '"focused"', 'preference', 'inference')
ON CONFLICT (key) DO UPDATE SET 
    value = EXCLUDED.value,
    updated_at = NOW();
