-- ============================================================================
-- ATHENA CANONICAL SCHEMA v2.0
-- ============================================================================
-- This is THE canonical schema for Athena's memory system.
-- All other schema files should be considered legacy.
-- 
-- Tables:
--   1. memory_events    - Append-only conversation/action log
--   2. memory_facts     - Durable facts about the user
--   3. memory_chunks    - Embeddings for semantic search
--   4. agent_runs       - Observability/telemetry records
--   5. user_facts       - (Legacy alias, kept for compatibility)
-- ============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "vector";

-- ============================================================================
-- 1. MEMORY_EVENTS (Append-only conversation log)
-- ============================================================================
-- Every user message, assistant response, and tool call is logged here.
-- This is the source of truth for conversation history.

CREATE TABLE IF NOT EXISTS memory_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL DEFAULT 'default',
    session_id TEXT NOT NULL DEFAULT 'default',
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system', 'tool')),
    content TEXT NOT NULL,
    metadata_json JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_memory_events_user_session 
    ON memory_events(user_id, session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_events_created 
    ON memory_events(created_at DESC);

ALTER TABLE memory_events ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to memory_events" ON memory_events;
    CREATE POLICY "Full access to memory_events" ON memory_events 
        FOR ALL USING (true) WITH CHECK (true);
END $$;

-- ============================================================================
-- 2. MEMORY_FACTS (Durable user facts)
-- ============================================================================
-- Long-lived facts about the user: preferences, profile info, goals.
-- Updated via upsert, not append-only.

CREATE TABLE IF NOT EXISTS memory_facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL DEFAULT 'default',
    key TEXT NOT NULL,
    value_json JSONB NOT NULL,
    category TEXT DEFAULT 'preference',  -- preference, personal, goal, system
    confidence REAL DEFAULT 1.0 CHECK (confidence >= 0 AND confidence <= 1),
    source TEXT DEFAULT 'inference',     -- inference, explicit, system
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    UNIQUE(user_id, key)
);

CREATE INDEX IF NOT EXISTS idx_memory_facts_user ON memory_facts(user_id);
CREATE INDEX IF NOT EXISTS idx_memory_facts_category ON memory_facts(category);

-- Auto-update timestamp trigger
CREATE OR REPLACE FUNCTION update_memory_facts_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_memory_facts_modtime ON memory_facts;
CREATE TRIGGER update_memory_facts_modtime
    BEFORE UPDATE ON memory_facts
    FOR EACH ROW
    EXECUTE FUNCTION update_memory_facts_timestamp();

ALTER TABLE memory_facts ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to memory_facts" ON memory_facts;
    CREATE POLICY "Full access to memory_facts" ON memory_facts 
        FOR ALL USING (true) WITH CHECK (true);
END $$;

-- ============================================================================
-- 3. MEMORY_CHUNKS (Semantic search embeddings)
-- ============================================================================
-- Chunked documents with vector embeddings for RAG.
-- Uses pgvector for similarity search.

CREATE TABLE IF NOT EXISTS memory_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL DEFAULT 'default',
    source TEXT NOT NULL,           -- 'conversation', 'document', 'note'
    chunk_text TEXT NOT NULL,
    embedding VECTOR(768),          -- Adjust dimension based on model
    metadata_json JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- HNSW index for fast similarity search
CREATE INDEX IF NOT EXISTS idx_memory_chunks_embedding 
    ON memory_chunks USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_memory_chunks_user 
    ON memory_chunks(user_id);
CREATE INDEX IF NOT EXISTS idx_memory_chunks_source 
    ON memory_chunks(source);

ALTER TABLE memory_chunks ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to memory_chunks" ON memory_chunks;
    CREATE POLICY "Full access to memory_chunks" ON memory_chunks 
        FOR ALL USING (true) WITH CHECK (true);
END $$;

-- Function for similarity search
CREATE OR REPLACE FUNCTION match_memory_chunks(
    query_embedding VECTOR(768),
    match_threshold FLOAT DEFAULT 0.7,
    match_count INT DEFAULT 8,
    filter_user_id TEXT DEFAULT NULL
)
RETURNS TABLE (
    id BIGINT,
    user_id TEXT,
    source TEXT,
    chunk_text TEXT,
    metadata_json JSONB,
    similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        mc.id,
        mc.user_id,
        mc.source,
        mc.chunk_text,
        mc.metadata_json,
        1 - (mc.embedding <=> query_embedding) AS similarity
    FROM memory_chunks mc
    WHERE 
        (filter_user_id IS NULL OR mc.user_id = filter_user_id)
        AND 1 - (mc.embedding <=> query_embedding) > match_threshold
    ORDER BY mc.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- ============================================================================
-- 3.5. AGENT_STATES (Legacy Persistence)
-- ============================================================================
-- Key-value store for agent state persistence. 
-- Required by services/memory_core.py

CREATE TABLE IF NOT EXISTS agent_states (
    agent_name TEXT NOT NULL,
    key TEXT NOT NULL,
    value JSONB DEFAULT '{}'::JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    PRIMARY KEY (agent_name, key)
);

CREATE OR REPLACE FUNCTION update_agent_states_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_agent_states_modtime ON agent_states;
CREATE TRIGGER update_agent_states_modtime
    BEFORE UPDATE ON agent_states
    FOR EACH ROW
    EXECUTE FUNCTION update_agent_states_timestamp();

ALTER TABLE agent_states ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to agent_states" ON agent_states;
    CREATE POLICY "Full access to agent_states" ON agent_states FOR ALL USING (true) WITH CHECK (true);
END $$;

-- ============================================================================
-- 4. AGENT_RUNS (Observability/Telemetry)
-- ============================================================================
-- Track every agent execution for debugging and cost monitoring.

CREATE TABLE IF NOT EXISTS agent_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL,
    user_id TEXT DEFAULT 'default',
    session_id TEXT,
    agent_name TEXT NOT NULL,
    model_used TEXT,
    tokens_in INTEGER DEFAULT 0,
    tokens_out INTEGER DEFAULT 0,
    cost_estimate NUMERIC(10, 6) DEFAULT 0,
    latency_ms INTEGER,
    status TEXT DEFAULT 'started' CHECK (status IN ('started', 'completed', 'failed')),
    error_message TEXT,
    metadata_json JSONB DEFAULT '{}'::JSONB,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_agent_runs_run_id ON agent_runs(run_id);
CREATE INDEX IF NOT EXISTS idx_agent_runs_agent ON agent_runs(agent_name);
CREATE INDEX IF NOT EXISTS idx_agent_runs_started ON agent_runs(started_at DESC);

ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY;
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Full access to agent_runs" ON agent_runs;
    CREATE POLICY "Full access to agent_runs" ON agent_runs 
        FOR ALL USING (true) WITH CHECK (true);
END $$;

-- ============================================================================
-- 5. USER_FACTS (Legacy compatibility alias)
-- ============================================================================
-- This view provides backward compatibility with existing code that uses
-- the user_facts table directly. Maps to memory_facts.
-- ============================================================================
-- 5. USER_FACTS (Legacy compatibility alias)
-- ============================================================================
-- This handled the "user_facts is not a view" error by checking if a legacy
-- user_facts TABLE exists, backing it up, migrating data, and then replacing
-- it with a View.

DO $$ 
BEGIN
    -- Check if user_facts exists AND is a table (not a view)
    IF EXISTS (
        SELECT FROM pg_tables 
        WHERE schemaname = 'public' AND tablename = 'user_facts'
    ) THEN
        RAISE NOTICE 'Legacy user_facts table detected. Renaming and migrating data...';
        
        -- 1. Rename the legacy table
        ALTER TABLE user_facts RENAME TO user_facts_legacy_backup;
        
        -- 2. Migrate data to the new memory_facts table
        --    Map 'value' (legacy) to 'value_json' (new)
        INSERT INTO memory_facts (user_id, key, value_json, category, confidence, source, created_at, updated_at)
        SELECT 
            'default', 
            key, 
            value, 
            category, 
            confidence, 
            source, 
            created_at, 
            updated_at
        FROM user_facts_legacy_backup
        ON CONFLICT (user_id, key) DO NOTHING;
        
        RAISE NOTICE 'Data migration complete. user_facts is now user_facts_legacy_backup.';
    END IF;
END $$;

-- Now safe to create the view
CREATE OR REPLACE VIEW user_facts AS
SELECT 
    id,
    key,
    value_json AS value,
    category,
    confidence,
    source,
    created_at,
    updated_at
FROM memory_facts
WHERE user_id = 'default';

-- ============================================================================
-- MIGRATION: Initial data (idempotent)
-- ============================================================================

INSERT INTO memory_facts (user_id, key, value_json, category, source) VALUES
    ('default', 'name', '"Drew"', 'personal', 'system'),
    ('default', 'location', '{"city": "Minneapolis", "state": "Minnesota", "timezone": "America/Chicago"}', 'personal', 'system'),
    ('default', 'pets', '[{"name": "Sushi", "type": "cat"}, {"name": "Astro", "type": "cat"}]', 'personal', 'system'),
    ('default', 'partner', '{"name": "Skylar"}', 'personal', 'system'),
    ('default', 'pc_setup', '{"os": "Windows 11", "shell": "PowerShell"}', 'technical', 'system'),
    ('default', 'interests', '["anime", "tech", "gaming", "AI", "finance"]', 'preference', 'system')
ON CONFLICT (user_id, key) DO UPDATE SET 
    value_json = EXCLUDED.value_json,
    updated_at = NOW();
