#!/usr/bin/env python3
"""
╔═══════════════════════════════════════════════════════════════════════════════╗
║                       A G E N T   F A C T O R Y                               ║
║                          "The Builder"                                         ║
║                                                                               ║
║  Division V: Expansion - GOD MODE                                             ║
║  Uses Claude 3.5 Sonnet to generate new agents on-the-fly                     ║
╚═══════════════════════════════════════════════════════════════════════════════╝

When a user requests `/check_crypto` and no such agent exists, Athena doesn't say
"Command not found." She says: "Building agent now..." and CREATES it using Claude.

Usage:
  python agent_factory.py --task "Scrape ETH price from CoinGecko"
  python agent_factory.py --task "Check if my server is up" --name "uptime"
"""

import os
import sys
import re
import ast
import argparse
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Optional, Tuple

from dotenv import load_dotenv
load_dotenv()

# =============================================================================
# CONFIGURATION
# =============================================================================

# Paths
BASE_DIR = Path(__file__).parent.parent
AGENTS_DIR = BASE_DIR / "agents"

# Ensure agents directory exists
AGENTS_DIR.mkdir(exist_ok=True)

# Claude API
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")

# Agent template for consistent structure
AGENT_TEMPLATE = '''#!/usr/bin/env python3
"""
{docstring}

Auto-generated by Athena Agent Factory
Generated: {timestamp}
"""

import os
import sys
import argparse
from pathlib import Path

# Add parent for imports if needed
sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv()

{code}

if __name__ == "__main__":
    main()
'''


# =============================================================================
# CLAUDE SYSTEM PROMPT
# =============================================================================

CLAUDE_SYSTEM_PROMPT = """You are an expert Python developer for Project Athena.

Your task is to write a COMPLETE, STANDALONE Python script (Spoke Agent) that fulfills the user's request.

**ARCHITECTURAL RULES (The Scientist Model):**
1.  **Output Contract**: Agents must print results in a structured format:
    *   **OBSERVATION**: What was found/seen (Facts).
    *   **HYPOTHESIS**: Interpretation of facts (if applicable).
    *   **RECOMMENDATION**: Actionable advice.
    *   **EVIDENCE**: References/IDs (NOT raw sensitive data).
2.  **Memory Access**:
    *   Agents are **Hub-Only Write**. Do not write to files/DBs directly unless it's a specific cache.
    *   Propose memory updates via standard output (e.g., "SUGGEST_MEMORY_UPDATE: ...").
3.  **Privacy (Evidence Vault)**:
    *   NEVER print raw private messages, exact addresses, or sensitive health data to stdout unless explicitly requested.
    *   Store/Reference sensitive data by ID or reference only.

**STRICT CODE REQUIREMENTS:**
1. Use `argparse` for command-line arguments.
2. Create a `main()` function.
3. Use ONLY standard library + `requests`, `beautifulsoup4`, `feedparser`, `httpx`, `rich`.
4. Include proper error handling.
5. **No Markdown** in output (return RAW Python code).
6. Start directly with imports.
"""


# =============================================================================
# CLAUDE API CLIENT
# =============================================================================

def call_claude(task_description: str) -> Optional[str]:
    """
    Call Claude 3.5 Sonnet to generate agent code.
    
    Args:
        task_description: What the agent should do
        
    Returns:
        Generated Python code or None on error
    """
    if not ANTHROPIC_API_KEY:
        print("❌ ANTHROPIC_API_KEY not set in .env")
        return None
    
    try:
        import httpx
        
        response = httpx.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": ANTHROPIC_API_KEY,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json"
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 4096,
                "system": CLAUDE_SYSTEM_PROMPT,
                "messages": [
                    {
                        "role": "user",
                        "content": f"Create a Python script that does the following:\n\n{task_description}\n\nRemember: Return ONLY executable Python code, no markdown."
                    }
                ]
            },
            timeout=60.0
        )
        
        response.raise_for_status()
        data = response.json()
        
        # Extract text from response
        content = data.get("content", [])
        if content and len(content) > 0:
            return content[0].get("text", "")
        
        return None
        
    except ImportError:
        print("❌ httpx not installed. Run: pip install httpx")
        return None
    except Exception as e:
        print(f"❌ Claude API error: {e}")
        return None


# =============================================================================
# CODE VALIDATION
# =============================================================================

def extract_code(raw_response: str) -> str:
    """
    Extract clean Python code from Claude's response.
    Handles cases where Claude might include markdown despite instructions.
    """
    code = raw_response.strip()
    
    # Remove markdown code blocks if present
    if "```python" in code:
        match = re.search(r'```python\n(.*?)```', code, re.DOTALL)
        if match:
            code = match.group(1)
    elif "```" in code:
        match = re.search(r'```\n?(.*?)```', code, re.DOTALL)
        if match:
            code = match.group(1)
    
    return code.strip()


def validate_syntax(code: str) -> Tuple[bool, str]:
    """
    Validate Python syntax using ast.parse().
    
    Returns:
        Tuple of (is_valid, error_message)
    """
    try:
        ast.parse(code)
        return True, ""
    except SyntaxError as e:
        return False, f"Syntax error at line {e.lineno}: {e.msg}"


def validate_structure(code: str) -> Tuple[bool, str]:
    """
    Validate that code has required structure (main function, argparse).
    """
    if "def main(" not in code:
        return False, "Missing main() function"
    
    if "argparse" not in code and "ArgumentParser" not in code:
        return False, "Missing argparse usage"
    
    return True, ""


# =============================================================================
# AGENT GENERATION
# =============================================================================

def generate_agent_name(task: str) -> str:
    """Generate a snake_case agent name from task description."""
    # Extract key words
    words = re.findall(r'\b[a-zA-Z]+\b', task.lower())
    
    # Common action words
    actions = {"check", "get", "fetch", "scrape", "monitor", "track", "find", "search", "scan", "analyze"}
    
    # Find action and subject
    action = None
    subject = None
    
    for word in words:
        if word in actions and not action:
            action = word
        elif word not in {"the", "a", "an", "to", "for", "from", "of", "my", "and", "or"} and not subject:
            if action:  # Only set subject after finding action
                subject = word
    
    if action and subject:
        return f"{action}_{subject}"
    elif subject:
        return f"check_{subject}"
    else:
        return f"agent_{datetime.now().strftime('%H%M%S')}"


def create_agent(task: str, name: Optional[str] = None, auto_run: bool = False, run_args: str = "") -> dict:
    """
    Generate a new agent using Claude.
    
    Args:
        task: Description of what the agent should do
        name: Optional custom name for the agent
        auto_run: Whether to run the agent after creation
        run_args: Arguments to pass if auto-running
        
    Returns:
        Result dict with success status, path, and any output
    """
    print(f"🏭 Agent Factory: Building new agent...")
    print(f"📋 Task: {task}")
    
    # Generate name if not provided
    agent_name = name or generate_agent_name(task)
    agent_name = re.sub(r'[^a-z0-9_]', '', agent_name.lower())
    
    if not agent_name.endswith('.py'):
        agent_name += '.py'
    
    agent_path = AGENTS_DIR / agent_name
    
    print(f"📝 Agent name: {agent_name}")
    
    # Call Claude to generate code
    print("🤖 Calling Claude 3.5 Sonnet...")
    raw_code = call_claude(task)
    
    if not raw_code:
        return {"success": False, "error": "Claude API call failed"}
    
    # Extract and clean code
    code = extract_code(raw_code)
    
    # Validate syntax
    is_valid, error = validate_syntax(code)
    if not is_valid:
        print(f"⚠️ Syntax validation failed: {error}")
        print("🔧 Attempting to fix...")
        # Could add retry logic here
        return {"success": False, "error": f"Generated code has syntax errors: {error}"}
    
    # Validate structure
    is_valid, error = validate_structure(code)
    if not is_valid:
        print(f"⚠️ Structure validation: {error}")
        # Non-fatal, continue anyway
    
    # Write to file
    try:
        with open(agent_path, 'w', encoding='utf-8') as f:
            f.write(code)
        print(f"✅ Agent created: {agent_path}")
    except Exception as e:
        return {"success": False, "error": f"Failed to write file: {e}"}
    
    result = {
        "success": True,
        "path": str(agent_path),
        "name": agent_name,
        "code_lines": len(code.split('\n'))
    }
    
    # Auto-run if requested
    if auto_run:
        print(f"🚀 Auto-running agent...")
        try:
            cmd = [sys.executable, str(agent_path)]
            if run_args:
                cmd.extend(run_args.split())
            
            run_result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=30,
                cwd=str(BASE_DIR)
            )
            
            result["output"] = run_result.stdout or run_result.stderr
            result["return_code"] = run_result.returncode
            
            if run_result.returncode == 0:
                print(f"✅ Agent executed successfully!")
            else:
                print(f"⚠️ Agent returned code {run_result.returncode}")
            
            if run_result.stdout:
                print("\n--- Agent Output ---")
                print(run_result.stdout)
            
        except subprocess.TimeoutExpired:
            result["output"] = "Execution timed out (30s)"
            print("⏰ Agent execution timed out")
        except Exception as e:
            result["output"] = f"Execution error: {e}"
            print(f"❌ Execution error: {e}")
    
    return result


# =============================================================================
# CLI
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Athena Agent Factory - Generate agents using Claude AI"
    )
    
    parser.add_argument(
        "--task", "-t",
        type=str,
        required=True,
        help="Description of what the agent should do"
    )
    
    parser.add_argument(
        "--name", "-n",
        type=str,
        help="Custom name for the agent (default: auto-generated)"
    )
    
    parser.add_argument(
        "--run", "-r",
        action="store_true",
        help="Auto-run the agent after creation"
    )
    
    parser.add_argument(
        "--args", "-a",
        type=str,
        default="",
        help="Arguments to pass when auto-running"
    )
    
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output result as JSON"
    )
    
    args = parser.parse_args()
    
    result = create_agent(
        task=args.task,
        name=args.name,
        auto_run=args.run,
        run_args=args.args
    )
    
    if args.json:
        import json
        print(json.dumps(result, indent=2))
    else:
        if result["success"]:
            print(f"\n🎉 Agent ready at: {result['path']}")
            print(f"   Lines of code: {result['code_lines']}")
        else:
            print(f"\n❌ Failed: {result.get('error', 'Unknown error')}")


if __name__ == "__main__":
    main()
